source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'rails-api'
gem 'mysql2'
gem 'bcrypt', '~> 3.1.7'
gem 'jbuilder'

gem 'octokit'
gem 'faraday-http-cache'
gem 'treetop'

group :development do
  gem 'spring'
end

group :test, :development do
  gem 'pry-rails'
  gem 'faker'
  gem 'rspec-rails'
end

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development
