source 'https://rubygems.org'


gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development


gem 'mysql2'

gem 'octokit'
gem 'faraday-http-cache'

gem 'pry-rails'

gem 'treetop'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
